### ISSUE TITLE
Content Download Taking too long when Connection: "keep-alive"

### ISSUE THREAD

**Issue by emiliowl** [waterlink/rack-reverse-proxy#33]
I've configured 3 Rails App to be my backend and, to avoid configuring nginx on localhost, I hosted my frontend app inside an Rails App that works as reverse proxy.

Everything works fine, except the fact that each request takes at least 20 seconds to respond.
Looking in detail at these requests, I've found this curl to simulate my browser requests:

curl 'http://localhost:3000/iss_towns/7175/history.json' -H 'Host: localhost:3000' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'X-XSRF-TOKEN: dZ1BnjPkR47qsDPTx5HvifkkBPy2H9vpogrEh4L98vcdls8HyZqj7asSvW0kGLOYfiMApyxhs4IGgMnAp6a8Ww==' -H 'Referer: http://localhost:3000/' -H 'Cookie: XSRF-TOKEN=dZ1BnjPkR47qsDPTx5HvifkkBPy2H9vpogrEh4L98vcdls8HyZqj7asSvW0kGLOYfiMApyxhs4IGgMnAp6a8Ww%3D%3D; -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'

If I do the same request without -H 'Connection: keep-alive' everything works fine. Do you guys have some workaround or know which may be causing this issue?

Thanks a lot!

**Comment by waterlink** [comment]
Hi @emiliowl !

Thank you for reporting this issue. It is possible that we could remove `Connection: keep-alive` before proxying the request. I am not 100% sure what the implications are though..

**Comment by emiliowl** [comment]
I found this workaround to solve the problem:

---------------------------------------------------------------------------------------------------------------------------------------
Create a class to remove the HTTP_CONNECTION header before sending the request
---------------------------------------------------------------------------------------------------------------------------------------
    class HeaderDelete
      def initialize(app, options = {})
        @app, @options = app, options
      end

      def call(env)
        env['HTTP_CONNECTION'] = ""
        r = @app.call(env)
      end
    end
---------------------------------------------------------------------------------------------------------------------------------------
Register this class before the Rack::Runtime and the Rack::ReverseProxy
---------------------------------------------------------------------------------------------------------------------------------------
config.middleware.insert_before(Rack::Runtime, HeaderDelete)
config.middleware.insert_after(HeaderDelete, Rack::ReverseProxy) do

Thanks a lot!
