### ISSUE TITLE
[SSL] Read error: #<NoMethodError: undefined method `each' for "":String>

### ISSUE THREAD

**Issue by lucasgerard** [waterlink/rack-reverse-proxy#36]
Hi,

I'm using Rack::ReverseProxy on a Rails app which is pointed by a custom domain jeparticipe.bordeaux.fr, and redirect to another Rails app.

I'm using SSL on my custom domain so I've added the following configuration on the proxy app :

`use Rack::ReverseProxy do`
`reverse_proxy /^\/?(.*)$/, 'http://jetaide.herokuapp.com/$1', force_ssl: true, replace_response_host: true`
`end`

but I get the following error as I test the SSL redirection throught http://jeparticipe.bordeaux.fr:
Read error: #<NoMethodError: undefined method `each' for "":String> and you can fin attached the full trace.

Any idea where the problem could come from?

Thanks,

Lucas
![screen shot 2016-09-26 at 23 57 42](https://cloud.githubusercontent.com/assets/5589858/18853649/ad2d16d4-8446-11e6-83e8-5acac86db630.png)

**Comment by waterlink** [comment]
Is it happening on the server running rack-reverse-proxy or server running
rails app?

And it does feel strange, since stacktrace is coming from puma HTTP server.
lucasgerard <notifications@github.com> schrieb am Di., 27. Sep. 2016 um
12:10 AM:

**Comment by lucasgerard** [comment]
Hey, thanks for the reply

It's happening on the server running rack-reverse-proxy, which is Puma

**Comment by andrewhavens** [comment]
@lucasgerard That error message means that your rack response body object is not an array. Rack is trying to call `.each` on your response body. I'm guessing that the request is falling back to your default app. In the readme, it gives this example:

```ruby
app = proc do |env|
  [ 200, {'Content-Type' => 'text/plain'}, "b" ]
end
```
...but this is wrong because `"b"` is not an array. You can simply wrap the string in an array and it will work:

```ruby
app = proc do |env|
  [ 200, {'Content-Type' => 'text/plain'}, ["b"] ]
end
```

**Comment by krainboltgreene** [comment]
That's definitely the case, I've encountered this before.

**Comment by waterlink** [comment]
I have fixed the README to use `["b"]`.
