### ISSUE TITLE
ideal to always be very first middleware?

### ISSUE THREAD

**Issue by jjb** [waterlink/rack-reverse-proxy#39]
Thanks for a fantastically useful project!

Wouldn't it be ideal in almost all use cases for this to be the very first middleware, so that other middleware don't do useless computation? So then the recommendation would be:

```ruby
config.middleware.insert(0, Rack::ReverseProxy) 
```

**Comment by waterlink** [comment]
What do you think about having a recommended way to insert the middleware via a helper method? Something like: `Rack::ReverseProxy::Rails.configure` ?

Also, what about pure `Rack` application? Would it be possible to have a similar functionality?

**Comment by jjb** [comment]
You mean make a method which somehow automagically takes care of the insertion?

I don't think there will be a way to do this reliably. Different parts of an app might be "fighting" for middelware ordering, so it needs to be done by the developer as explicitly and simply as possible.

**Comment by jjb** [comment]
backing up a bit: i'm wondering why the readme suggests `insert_before(Rack::Lock`/`Rack::Runtime`, and what you think of suggesting to the user that it always be the very first middleware in most cases?

**Comment by jjb** [comment]
see #12 and #27 for reasons why it should be the very first middleware. those problems would have been avoided if it wasn't being run through deflater.

**Comment by waterlink** [comment]
> I don't think there will be a way to do this reliably. Different parts of an app might be "fighting" for middelware ordering, so it needs to be done by the developer as explicitly and simply as possible.

Agree
