### ISSUE TITLE
Location getting mangled

### ISSUE THREAD

**Issue by jjb** [waterlink/rack-reverse-proxy#40]
My rails app is on example.com, my wordpress blog is hosted on blog.example.com, and I'm using rack-reverse-proxy to stream the blog through example.com/blog.

I'm using `force_ssl` so I also have `replace_response_host`.

Most things are working pretty well, but on some wordpress actions the Location afterward gets mangled. example:

Wordpress produces: `users.php?update=add&id=16`

rack-reverse-proxy rewrites it as: `http://example.comusers.php?update=add&id=16`

The full URL should be: `http://example.com/blog/wp-admin/users.php?update=add&id=16`

Backing up a bit: I'm actually not sure what standalone `replace_response_host` is useful for, or why it ever has to run other than when redirecting `http` -> `https`.

Let me know what you think and I'll try to contribute a PR, either to code or documentation.

Thanks for a 🌈super helpful✨ project!

**Comment by waterlink** [comment]
These cues might be helpful here:

- https://github.com/waterlink/rack-reverse-proxy/blob/master/lib/rack_reverse_proxy/roundtrip.rb#L171
- https://github.com/waterlink/rack-reverse-proxy/blob/master/lib/rack_reverse_proxy/roundtrip.rb#L230
- and, possibly, this: https://github.com/waterlink/rack-reverse-proxy/blob/master/lib/rack_reverse_proxy/roundtrip.rb#L211-L216

**Comment by waterlink** [comment]
Thinking more about it:

It seems, currently rack-reverse-proxy assumes that `Location` header is always absolute, i.e.: starts from `/`. So it appends that `Location` header value as suffix to the `host`.

We will need to write a test for the case when the `Location` is relative, i.e.: does not start from `/`. In that case, it should construct a proper relative URI given current URI and `Location` header value.

**Comment by waterlink** [comment]
@jjb I hope I understood you correctly here: when you talk about "Location", do you mean location http header that is produced during redirects?

**Comment by jjb** [comment]
> when you talk about "Location", do you mean location http header that is produced during redirects?

yes

**Comment by jjb** [comment]
> In that case, it should construct a proper relative URI given current URI and Location header value.

Alas, we don't know what "current URI" is. 

A user can be on foo.com/bar and POST to foo.com/baz, get Location back of "hello". this means foo.com/bar/hello, but the only info rack-reverse-proxy knows is the request URI, foo.com/baz.

**Comment by jjb** [comment]
> What reason does it have to mutate location in the first place?

Okay right after I wrote that I realized the obvious answer is to transform blog.example.com into example.com/blog, the entire purpose of the library :-D

okay so what about this solution: if a Location doesn't start with "http", never transform it?

**Comment by jjb** [comment]
😹
