### ISSUE TITLE
expected behavior for compressed responses?

### ISSUE THREAD

**Issue by jjb** [waterlink/rack-reverse-proxy#44]
None of my responses which are compressed on the source server end up compressed when coming back from the proxy server. I haven't investigated why this is yet. First wanted to ask, what is the expected behavior?

**Comment by waterlink** [comment]
I don't think there is any expectation there. From fresh perspective, it probably should come out compressed. Could also be configurable.

**Comment by jjb** [comment]
addressed by #52
